version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-notion-rss"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6khiref5byxf"
s3_prefix = "lambda-notion-rss"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
