AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  notion-rss

Globals:
  Function:
    Timeout: 850
    Environment:
      Variables:
        TZ: Asia/Tokyo

Resources:
  NotionRSSFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "lambda-notion-rss"
      CodeUri: ./lambda_rss
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Role: !GetAtt NotionRSSFunctionRole.Arn
      Events:
        RSSGetSchedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour) # 1時間毎
            Input: |
              {
                "region": "tokyo"
              }

  NotionRSSFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - !Ref NotionRSSFunctionPolicy

  NotionRSSFunctionPolicy:
      Type: AWS::IAM::ManagedPolicy
      Properties:
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogStream"
                  - "logs:CreateLogGroup"
                  - "logs:PutLogEvents"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "secretsmanager:GetSecretValue"
                  - "ssm:GetParameters"
                  - "ssm:GetParameter"
                Resource: "*"
