name: sam-deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    uses: /.github/workflows/sam-build.yml
    secrets: inherit

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
     contents: 'read'
     id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-OIDCRole
          role-session-name: SAMDeploySession

      - name: sam build
        run: sam build

      - name: sam deploy
        run: sam deploy --s3-bucket ${{ secrets.S3_BUCKET_NAME }} --no-confirm-changeset --no-fail-on-empty-changeset
